---
- name: Setup Config
  template:
    src: 'sample.conf_{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.j2'
    dest: '/tmp/sample.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: "{{ NAME_SERVICE_MANAGER }} restarted {{ NAME_DAEMON }}"
