---
- include_role:
    name: libraries
    tasks_from: service_disabled.yml
  with_items:
    - "{{ COMMON_DISABLE_SERVICES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_DISABLE_SERVICES | default([]) }}"
    - "{{ INVENTORY_DISABLE_SERVICES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_DISABLE_SERVICES | default([]) }}"

- include_role:
    name: libraries
    tasks_from: kernel_service_disabled.yml
  with_items:
    - "{{ COMMON_DISABLE_KERNEL_SERVICES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_DISABLE_KERNEL_SERVICES | default([]) }}"
    - "{{ INVENTORY_DISABLE_KERNEL_SERVICES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_DISABLE_KERNEL_SERVICES | default([]) }}"

- name: Remove Packages
  yum:
    name: "{{ item.NAME }}"
    state: 'removed'
    enablerepo: "{{ item.ENABLEREPO | default([base]) }}"
  with_items:
    - "{{ COMMON_REMOVE_PACKAGES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_REMOVE_PACKAGES | default([]) }}"
    - "{{ INVENTORY_REMOVE_PACKAGES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_REMOVE_PACKAGES | default([]) }}"

- name: Install Packages
  yum:
    name: "{{ item.NAME }}"
    state: 'installed'
    enablerepo: "{{ item.ENABLEREPO | default('base') }}"
  with_items:
    - "{{ COMMON_INSTALL_PACKAGES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_INSTALL_PACKAGES | default([]) }}"
    - "{{ INVENTORY_INSTALL_PACKAGES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_INSTALL_PACKAGES | default([]) }}"

- name: Pip Install Packages
  pip:
    name: "{{ item.NAME }}"
    state: 'present'
  with_items:
    - "{{ COMMON_PIP_INSTALL_PACKAGES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_PIP_INSTALL_PACKAGES | default([]) }}"
    - "{{ INVENTORY_PIP_INSTALL_PACKAGES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_PIP_INSTALL_PACKAGES | default([]) }}"

- name: Manage Groups
  group:
    name: "{{ item.NAME }}"
    gid: "{{ item.GID }}"
    local: "{{ item.LOCAL| default('no') }}"
    non_unique: "{{ item.NON_UNIQUE| default('no') }}"
    state: "{{ item.STATE| default('present') }}"
    system: "{{ item.SYSTEM | default('no') }}"
  with_items:
    - "{{ COMMON_GROUPS | default([]) }}"
    - "{{ COMMON_HOSTGROUP_GROUPS | default([]) }}"
    - "{{ INVENTORY_GROUPS | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_GROUPS | default([]) }}"

- name: Manage Users
  user:
    name: "{{ item.NAME }}"
    uid: "{{ item.UID }}"
    group: "{{ item.GROUP | default() }}"
    shell: "{{ item.SHELL | default('/sbin/nologin') }}"
    home: "{{ item.HOME | default('/home/' + item.NAME) }}"
    create_home: "{{ item.CREATE_HOME | default('yes') }}"
    password: "{{ item.PASSWORD | default() }}"
    comment: "{{ item.COMMENT | default() }}"
    update_password: "{{ item.UPDATE_PASSWORD | default('always') }}"
    state: "{{ item.STATE| default('present') }}"
  with_items:
    - "{{ COMMON_USERS | default([]) }}"
    - "{{ COMMON_HOSTGROUP_USERS | default([]) }}"
    - "{{ INVENTORY_USERS | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_USERS | default([]) }}"

- name: Manage Directory
  include_role:
    name: libraries
    tasks_from: mkdir.yml
  with_items:
    - "{{ COMMON_MKDIRS | default([]) }}"
    - "{{ COMMON_HOSTGROUP_MKDIRS | default([]) }}"
    - "{{ INVENTORY_MKDIRS | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_MKDIRS | default([]) }}"

- name: Copy files
  copy:
    src: "{{ item.SRC }}"
    dest: "{{ item.DEST }}"
    owner: "{{ item.OWNER }}"
    group: "{{ item.GROUP }}"
    mode: "{{ item.MODE }}"
  with_items:
    - "{{ COMMON_COPY_FILES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_COPY_FILES | default([]) }}"
    - "{{ INVENTORY_COPY_FILES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_COPY_FILES | default([]) }}"

- name: Template files
  template:
    src: "{{ item.SRC }}"
    dest: "{{ item.DEST }}"
    owner: "{{ item.OWNER }}"
    group: "{{ item.GROUP }}"
    mode: "{{ item.MODE }}"
  with_items:
    - "{{ COMMON_TEMPLATE_FILES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_TEMPLATE_FILES | default([]) }}"
    - "{{ INVENTORY_TEMPLATE_FILES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_TEMPLATE_FILES | default([]) }}"

- name: Make Symlinks
  file:
    src: "{{ item.SRC }}"
    path: "{{ item.PATH }}"
    state: link
  with_items:
    - "{{ COMMON_SYMLINKS | default([]) }}"
    - "{{ COMMON_HOSTGROUP_SYMLINKS | default([]) }}"
    - "{{ INVENTORY_SYMLINKS | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_SYMLINKS | default([]) }}"

- name: Delete files and directory
  file:
    path: "{{ item.PATH }}"
    state: absent
  with_items:
    - "{{ COMMON_DELETE_FILES | default([]) }}"
    - "{{ COMMON_HOSTGROUP_DELETE_FILES | default([]) }}"
    - "{{ INVENTORY_DELETE_FILES | default([]) }}"
    - "{{ INVENTORY_HOSTGROUP_DELETE_FILES | default([]) }}"
