---
- name: Check State "{{ DAEMON_NAME }}"
  command: "service {{ DAEMON_NAME }} status"
  register: service_status
  changed_when: False
  failed_when: False
  when: not ansible_check_mode

- name: Stopped "{{ DAEMON_NAME }}"
  command: echo "Stopped {{ DAEMON_NAME }}"
  notify: Service stopped {{ DAEMON_NAME }}
  when:
    - not ansible_check_mode
    - service_status.rc != 3
