---
- name: Check State "{{ DAEMON_NAME }}"
  command: "systemctl status {{ DAEMON_NAME }}"
  register: service_status
  changed_when: False
  failed_when: False
  when: not ansible_check_mode

# Start if serivce stop(rc != 0)
- name: Restarted "{{ DAEMON_NAME }}"
  command: echo "Restarted(started) {{ DAEMON_NAME }}"
  notify: Systemd started {{ DAEMON_NAME }}
  when:
    - not ansible_check_mode
    - service_status.rc != 0

# ReStart if serivce stop(rc == 0)
- name: Restarted "{{ DAEMON_NAME }}"
  command: echo "Restarted {{ DAEMON_NAME }}"
  notify: Systemd restarted {{ DAEMON_NAME }}
  when:
    - not ansible_check_mode
    - service_status.rc == 0
